FROM cluster-base

ARG spark_version=3.0.0
ARG hadoop_version=2.7
ARG spark_folder=spark-${spark_version}-bin-hadoop${hadoop_version}

RUN apt-get update -y && \
	apt-get install -y curl && \
	curl https://archive.apache.org/dist/spark/spark-${spark_version}/${spark_folder}.tgz -o spark.tgz && \
	tar -xf spark.tgz && \
	mv ${spark_folder} /usr/bin/ && \
	mkdir /usr/bin/${spark_folder}/logs && \
	rm spark.tgz

ENV SPARK_HOME /usr/bin/${spark_folder}
ENV SPARK_MASTER_HOST spark-master
ENV SPARK_MASTER_PORT 7077
ENV PYSPARK_PYTHON python3

WORKDIR ${SPARK_HOME}
