FROM cluster-base

ARG spark_version=3.0.0

RUN apt-get update -y && \
	apt-get install -y python3-pip && \
	pip3 install wget pyspark==${spark_version} jupyterlab

WORKDIR ${SHARED_WORKSPACE}

CMD jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.iopub_data_rate_limit=1.0e10